version: 2.1
jobs:
    build-current:
        docker:
            - image: cimg/base:current
              auth:
                  username: mydockerhub-user
                  password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                  name: Build current
                  command: |
                      DOCKER_BUILDKIT=1 docker build -f Dockerfile-verify-current --rm -t verifyusi/verify-env:current .
            - run:
                  name: publish current
                  command: |
                      echo $DOCKERHUB_PASS |docker login -u $DOCKER_USER --password-stdin
                      echo "docker push verifyusi/verify-env:current"

    build-starexec:
        docker:
            - image: cimg/base:current
              auth:
                  username: mydockerhub-user
                  password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                  name: build starexec
                  command: DOCKER_BUILDKIT=1 docker build -f Dockerfile-verify-starexec --rm -t verifyusi/verify-env:starexec .
            - run:
                  name: publish starexec
                  command: |
                      echo $DOCKERHUB_PASS |docker login -u $DOCKER_USER --password-stdin
                      echo "docker push verifyusi/verify-env:starexec"

workflows:
    build-test:
        jobs:
          - build-current:
            filters: &filters-build-test
              tags:
                only: /^v.*/
          - build-starexec:
            filters:
              <<: *filters-build-test


